# Numpy Challenge

This challenge involves writing/modifying a function, which accepts a numpy array of fixed size and transforms it into an expected output array.

Below we have provided 2 examples along with the expected return value.

In [1]:
import numpy as np
def transform(a):
    return a

transform(np.array([0.,1.0,1.3,1.3,2.,1.4,0.33,1.59,6.]))

array([0.  , 1.  , 1.3 , 1.3 , 2.  , 1.4 , 0.33, 1.59, 6.  ])

## Example 1

With input: `np.array([0.,1.0,1.3,1.3,2.,1.4,0.33,1.59,6.])`

Expected return value:

```
array([[0.33, 3.18, 6.  ],
       [2.6 , 2.  , 2.8 ],
       [0.  , 1.  , 2.6 ]], dtype=float16)
```

## Example 2

With input: `np.array([0.9,2.3,1.9,1.0,0.2,1.4,0.33,1.99,3.])`

Expected return value:

```
array([[0.33, 3.98, 3.  ],
       [1.  , 0.2 , 2.8 ],
       [0.9 , 2.3 , 3.8 ]], dtype=float16)
```